apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: graceful-trees-333301
  # artifacts:
  #   - image: us.gcr.io/graceful-trees-333301/auth
  #     context: auth
  #     docker:
  #       dockerfile: Dockerfile
  #     sync:
  #       manual:
  #         - src: "src/**/*.ts"
  #           dest: .
  #   - image: us.gcr.io/graceful-trees-333301/client
  #     context: client
  #     docker:
  #       dockerfile: Dockerfile
  #     sync:
  #       manual:
  #         - src: "**/*.js"
  #           dest: .
  #   - image: us.gcr.io/graceful-trees-333301/tickets
  #     context: tickets
  #     docker:
  #       dockerfile: Dockerfile
  #     sync:
  #       manual:
  #         - src: "src/**/*.ts"
  #           dest: .
  #   - image: us.gcr.io/graceful-trees-333301/orders
  #     context: orders
  #     docker:
  #       dockerfile: Dockerfile
  #     sync:
  #       manual:
  #         - src: "src/**/*.ts"
  #           dest: .
  #   - image: us.gcr.io/graceful-trees-333301/expiration
  #     context: expiration
  #     docker:
  #       dockerfile: Dockerfile
  #     sync:
  #       manual:
  #         - src: "src/**/*.ts"
  #           dest: .
  #   - image: us.gcr.io/graceful-trees-333301/payments
  #     context: payments
  #     docker:
  #       dockerfile: Dockerfile
  #     sync:
  #       manual:
  #         - src: "src/**/*.ts"
  #           dest: .
  artifacts:
    - image: thanhtrungtoan/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: thanhtrungtoan/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: thanhtrungtoan/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: thanhtrungtoan/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: thanhtrungtoan/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: thanhtrungtoan/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
